### PR TITLE
 Added more search qualifiers related to cars+trucks searches

### PR DESCRIPTION
**Pull request by unitpas**

### CODE REVIEW

**Comment by brozeph** [comment]
Clean PR, thanks @unitpas! Will merge now and prepare release this afternoon.

**Comment by unitpas** [comment]
I don't know why node 10 tests fail on http request, they pass in my local
 same node version

**Comment by brozeph** [comment]
Yes... super strange. Looking at it now... seems to be isolated to the Node.js 10.x tests

**Comment by brozeph** [comment]
update: I'm able to reproduce with Node `v10.16.0`

**Comment by unitpas** [comment]
Confirmed: reproduced on my local with v10.16.0. I will debug to see what's causing it

**Comment by brozeph** [comment]
Found the issue:

```javascript
{ Error: HTTP error received
    at IncomingMessage.<anonymous> (/Volumes/Data/Projects/brozeph/node-craigslist/node_modules/reqlib/dist/index.js:431:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  body:
   'This IP has been automatically blocked.\nIf you have questions, please email: blocks-b1557181822816873@craigslist.org\n',
  options:
   { hostname: 'seattle.craigslist.org',
     method: 'GET',
     path: '/search/sss?sort=rel&query=xbox',
     maxRedirectCount: 5,
     maxRetryCount: 3,
     timeout: 60000,
     headers: { 'Content-Length': 0, 'Content-Type': 'application/json' },
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'seattle.craigslist.org',
     port: null,
     hash: null,
     search: '?sort=rel&query=xbox',
     query: 'sort=rel&query=xbox',
     pathname: '/search/sss',
     href:
      'https://seattle.craigslist.org/search/sss?sort=rel&query=xbox' },
  state:
   { data: '',
     redirects: [ [Url] ],
     tries: 1,
     headers:
      { 'content-length': '117',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=86400' },
     statusCode: 403 } }
```

Essentially, Craigslist is blocking the IP of the request!

**Comment by unitpas** [comment]
Well, the tests should not touch real hosts, I saw you mocked the **request.get** method, how come the request is still happening ?

**Comment by brozeph** [comment]
Because it’s not a unit test, but rather a functional one (there exist a handful in the integration folder under tests). Still odd that failure is only occurring in v10.16.0, though. I’ve been continuing to look as time allows.

**Comment by unitpas** [comment]
maybe we should create an array of cities and randomize and distribute the
requests, its not the perfect formula because we could get some random
failures but I think its better than hammering just one host, what do you
think ?

**Comment by brozeph** [comment]
Ended up creating the array of cities, but also changed how the tests are ran via travis. To run the integration suite, `npm run test:all` should be used... travis now simply runs the unit tests.

Still seeing the odd behavior on Node v10.16.0, but not on v10.15.x - will reevaluate when the next Node version bump occurs.

**Comment by unitpas** [comment]
I tested on my local using node 12 and they pass. I suspect node 10.x sends
some header param by default and craigslist identify that as spam and
filters the request.

**Pull request merged**
